export enum Authority {
  UPDATE_STUDENTS = 'Update Students',
  ADD_STUDENTS = 'Add Students',
  ADD_TUTORS = 'Add Tutors',
  VIEW_TUTORS = 'View Tutors',
  UPDATE_TUTORS = 'Update Tutors',
  ADD_ROLES = 'Add Roles',
  VIEW_ROLES = 'View Roles',
  UPDATE_ROLES = 'Update Roles',
  ADD_COURSES = 'Add Courses',
  VIEW_COURSES = 'View Courses',
  UPDATE_COURSES = 'Update Courses',
  ADD_ASSESSMENTS =  'Add Assessments',
  VIEW_ASSESSMENTS = 'View Assessments',
  UPDATE_ASSESSMENTS = 'Update Assessments',
  ADD_ENROLLMENTS = 'Add Enrollments' ,
  VIEW_ENROLLMENTS = 'View Enrollments',
  UPDATE_ENROLLMENTS = 'Update Enrollments',
}